name: On Push Tags Workflows

on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Generate Release From Tag
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}'
          prerelease: false

  publish-npm:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: NPM Install
        run: npm install
      - name: NPM Continous Integration
        run: npm ci
      - name: NPM Build
        run: npm run-script build
      - name: NPM Version of the Readme
        run: mv NPM-README.md README.md
      - name: NPM Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    name: 'Publish to GitHub'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@open-template-hub'

      - name: NPM Install
        run: npm install
      - name: NPM Continous Integration
        run: npm ci
      - name: NPM Build
        run: npm run-script build
      - name: NPM Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.MASTER_BRANCH_ACCESS_TOKEN}}
